server:
  port: 8085
spring:
    application:
        name: spring-cloud-config-client
    cloud:
        config:
        uri: http://localhost:8080
        fail-fast: true
        name: spring-cloud-config-client
        profile: dev
cip:
  db:
    enable: true
    name: cipDB